[package]
name = "async-autotiling"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
anyhow = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
swayipc-async = "2"
regex = "1.10"

